### ISSUE TITLE
Non-issue:  MHI FDUA system 

### ISSUE THREAD

**Issue by Meesen0743** [roscoe81/Aircon-Controller#3]
Hi there,

Just stumbled upon your project here and was wondering if you had any idea if it would work with a Mitsubishi Heavy Industries 'FDUA100VNP1VF2' ducted system (RC-EX controller (2 wire))? 

About to check if my indoor unit has a CNB port on the main board but from memory when I installed the unit it did not as the communications were over 2 wires that also power the RC-EX3 controller.

If your project is not compatible could we possibly have a chat about possible routes I could take to get something working? 

Thanks for your time.

**Comment by roscoe81** [comment]
I had a quick look at the RC-EX3 controller and it doesn’t look as if it’s compatible with my project. I did notice that it has a USB port for interfacing to a computer but I couldn’t find any relevant specs. You might be able track it down and modify my project’s hardware and software to suit. An alternative is to use the CNT connector that would allow simple on/off control and system monitoring but that will also require hardware changes (relays and drivers) and software changes to my project. In fact, I did originally have the CNT connector as a fallback if I wasn’t able to reverse engineer the CNB port’s protocol.
